name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Build the gem
      run: gem build krane.gemspec

    - name: Publish the gem to GitHub Packages
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: gem push *.gem --host=https://rubygems.pkg.github.com/${{ github.repository_owner }}

