name: Krane CI

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    name: "Tests (${{matrix.test_suite}}) - Ruby ${{ matrix.ruby }} with Kubernetes ${{ matrix.kubernetes_version }}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2.2"
        kubernetes_version:
          - "1.23.17"
        test_suite:
          - "unit_test"
          - "serial_integration_test"
          - "integration_test"
        include:
          - kubernetes_version: "1.23.17"
            kind_image: "kindest/node:v1.23.17@sha256:eb33093b461ffee7614ca65a39ac0fb57982e1407dc38df4df92811c4fbcb687"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup kubectl ${{ matrix.kubernetes_version }}
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/bin"
          curl -o "${GITHUB_WORKSPACE}/bin/kubectl" -LO "https://dl.k8s.io/release/v${{ matrix.kubernetes_version }}/bin/linux/amd64/kubectl"
          chmod +x "${GITHUB_WORKSPACE}/bin/kubectl"
          echo "PATH=$GITHUB_WORKSPACE/bin:${PATH}" >> $GITHUB_ENV

      - name: Create kind cluster for ${{ matrix.kubernetes_version }}
        run: |
          kind create cluster --image=${{ matrix.kind_image }}

      - name: Run tests
        run: |
          bin/test ${{matrix.test_suite}}
